file=open("tops1.txt","w")
file.write("This is file management write operation in python.")
file.close()
print("File Written Successfully")
print("-"*70)

file=open("tops1.txt","r")
print(file.read())
file.close()
print("-"*70)

file=open("tops1.txt","a")
file.write("\nThis is file is now appended.")
file.close()
print("File Written Successfully")
print("-"*70)

file=open("tops1.txt","r")
print(file.read())
file.close()
print("-"*70)

file=open("tops1.txt","w+")
file.write("This is file management write operation in python.")
print("Cursor Position : ",file.tell())
file.seek(0)
print("File Data : ",file.read())
file.close()
print("-"*70)

